#!/usr/bin/env python3
"""Build a lightweight lookup table for Pokémon Showdown sprite IDs."""

from __future__ import annotations

import json
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
POKEDEX_PATH = REPO_ROOT / "data" / "showdown" / "pokedex.json"
TARGET_PATH = REPO_ROOT / "frontend" / "web" / "src" / "assets" / "pokemon-sprites.ts"


def to_id(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "", value.lower())


def compute_sprite_id(record: dict) -> str:
    name = record["name"]
    base_species = record.get("baseSpecies") or name
    forme = record.get("forme") or ""
    base_id = to_id(base_species)
    if base_species != name and forme:
        return f"{base_id}-{to_id(forme)}"
    if base_species != name:
        return to_id(name)
    return base_id


def main() -> None:
    if not POKEDEX_PATH.exists():
        raise SystemExit("pokedex.json is missing. Run scripts/fetch_showdown_data.py first.")

    data = json.loads(POKEDEX_PATH.read_text(encoding="utf-8"))
    lookup: dict[str, str] = {}
    for record in data.values():
        name = record.get("name")
        if not name:
            continue
        normalized = to_id(name)
        sprite_id = compute_sprite_id(record)
        lookup[normalized] = sprite_id

    lines = [
        "// Auto-generated by scripts/export_sprite_map.py",
        "// Data source: https://play.pokemonshowdown.com/data/pokedex.js",
        "",
        "export const SPRITE_ID_LOOKUP: Record<string, string> = {",
    ]
    for key in sorted(lookup):
        lines.append(f'  "{key}": "{lookup[key]}",')
    lines.append("};")
    lines.append("")
    lines.append('export const SPRITE_BASE_URL = "https://play.pokemonshowdown.com/sprites/gen5";')
    lines.append("")
    lines.append("export function normalizeName(value: string): string {")
    lines.append("  return value.toLowerCase().replace(/[^a-z0-9]+/g, '');")
    lines.append("}")
    lines.append("")
    lines.append("export function buildSpriteUrl(displayName: string): string | null {")
    lines.append("  const normalized = normalizeName(displayName);")
    lines.append("  if (!normalized) return null;")
    lines.append("  const spriteId = SPRITE_ID_LOOKUP[normalized] ?? normalized;")
    lines.append("  if (!spriteId) return null;")
    lines.append("  return `${SPRITE_BASE_URL}/${spriteId}.png`;")
    lines.append("}")
    lines.append("")

    TARGET_PATH.parent.mkdir(parents=True, exist_ok=True)
    TARGET_PATH.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
